export const GET_MY_ACCOUNTS = 'GET_MY_ACCOUNTS';
export const SET_MY_ACCOUNTS = 'SET_MY_ACCOUNTS';
export const SAVE_ACCOUNT = 'SAVE_ACCOUNT';
export const SET_SAVED_ACCOUNT = 'SET_SAVED_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const SET_DELETED_ACCOUNT = 'SET_DELETED_ACCOUNT';
